<?php

declare(strict_types=1);

namespace Catidegla\AgentKit\Mcp;

use Catidegla\AgentKit\Exposure\Resource;

/**
 * Emits laravel/mcp tool classes from an exposed resource.
 *
 * String rendering only, with no filesystem in it, so the output can be
 * asserted in a test without writing anything anywhere.
 *
 * The generated bodies delegate straight to the resource and do nothing else.
 * That is the point rather than laziness: field allowlists, per record
 * authorization, ceilings, relation rules and the audit trail all live in the
 * resource, and any logic added to a tool sits outside every one of them. The
 * generated file says so at the top, because the first instinct on opening a
 * generated class is to start editing it.
 */
final class ToolGenerator
{
    public function __construct(
        private readonly string $namespace = 'App\\Mcp\\Tools',
    ) {}

    /**
     * One class per declared ability.
     *
     * @return array<string, string> class name to PHP source
     */
    public function forResource(Resource $resource): array
    {
        $out = [];

        foreach ($resource->abilities() as $ability) {
            if (! in_array($ability, ['list', 'get', 'search'], true)) {
                continue;
            }

            $out[$this->className($resource, $ability)] = $this->render($resource, $ability);
        }

        return $out;
    }

    public function className(Resource $resource, string $ability): string
    {
        return class_basename($resource->modelClass).ucfirst($ability).'Tool';
    }

    /** The name the agent sees, kebab cased the way laravel/mcp derives its own. */
    public function toolName(Resource $resource, string $ability): string
    {
        return str_replace('_', '-', $resource->name()).'-'.$ability;
    }

    public function title(Resource $resource, string $ability): string
    {
        return ucfirst($ability).' '.class_basename($resource->modelClass).' records';
    }

    private function render(Resource $resource, string $ability): string
    {
        $model = class_basename($resource->modelClass);
        $imports = $this->imports($resource);
        $schema = $this->schema($resource, $ability);

        return implode("\n", [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            'namespace '.$this->namespace.';',
            '',
            $imports,
            '',
            '/**',
            ' * Generated by agent-kit from the #[AgentResource] attribute on '.$model.'.',
            ' *',
            ' * The body delegates to the resource and does nothing else, on purpose. The',
            ' * field allowlist, the per record policy check, the result ceiling, the',
            ' * relation rules and the audit trail all live there, so anything added here',
            ' * runs outside every one of them.',
            ' *',
            ' * To change what this exposes, change the attribute on '.$model.' and run',
            ' * `php artisan agent-kit:mcp --force` again.',
            ' */',
            '#[Name('.var_export($this->toolName($resource, $ability), true).')]',
            '#[Title('.var_export($this->title($resource, $ability), true).')]',
            '#[Description('.var_export($resource->description(), true).')]',
            'final class '.$this->className($resource, $ability).' extends Tool',
            '{',
            '    public function handle(Request $request, Registry $registry): Response',
            '    {',
            $this->handle($resource, $ability),
            '    }',
            '',
            '    /**',
            '     * @return array<string, \\Illuminate\\JsonSchema\\Types\\Type>',
            '     */',
            '    public function schema(JsonSchema $schema): array',
            '    {',
            '        return [',
            $schema,
            '        ];',
            '    }',
            '}',
            '',
        ]);
    }

    private function imports(Resource $resource): string
    {
        $lines = [
            'use '.$resource->modelClass.';',
            'use Catidegla\\AgentKit\\Registry;',
            'use Illuminate\\Contracts\\JsonSchema\\JsonSchema;',
            'use Laravel\\Mcp\\Request;',
            'use Laravel\\Mcp\\Response;',
            'use Laravel\\Mcp\\Server\\Attributes\\Description;',
            'use Laravel\\Mcp\\Server\\Attributes\\Name;',
            'use Laravel\\Mcp\\Server\\Attributes\\Title;',
            'use Laravel\\Mcp\\Server\\Tool;',
        ];

        sort($lines);

        return implode("\n", $lines);
    }

    private function handle(Resource $resource, string $ability): string
    {
        $model = class_basename($resource->modelClass);
        $include = $resource->relations() === [] ? '' : "\n            \$request->array('include'),";

        // The signed in user is passed straight through. An agent acting as the
        // application rather than as a person is the failure this package
        // exists to prevent, so the tool never resolves a user of its own.
        if ($ability === 'get') {
            return implode("\n", [
                '        $row = $registry->resource('.$model.'::class)->get(',
                '            $request->user(),',
                "            \$request->get('id'),".$include,
                '        );',
                '',
                '        if ($row === null) {',
                '            // A denied record and a missing one answer identically, so the',
                '            // tool cannot be used to discover which ids exist.',
                "            return Response::error('No such record, or it is not yours to read.');",
                '        }',
                '',
                '        return Response::structured($row);',
            ]);
        }

        if ($ability === 'search') {
            return implode("\n", [
                '        $result = $registry->resource('.$model.'::class)->search(',
                '            $request->user(),',
                "            (string) \$request->get('query'),",
                "            \$request->integer('limit') ?: null,".$include,
                '        );',
                '',
                '        return Response::structured($result);',
            ]);
        }

        $filters = $resource->projection->filterable() === []
            ? '            [],'
            : "            \$request->array('filters'),";

        return implode("\n", [
            '        $result = $registry->resource('.$model.'::class)->list(',
            '            $request->user(),',
            $filters,
            "            \$request->integer('limit') ?: null,".$include,
            '        );',
            '',
            '        return Response::structured($result);',
        ]);
    }

    private function schema(Resource $resource, string $ability): string
    {
        $lines = [];

        if ($ability === 'get') {
            $lines[] = $this->property('id', 'string', 'Identifier of the record to fetch.', true);
        }

        if ($ability === 'search') {
            $lines[] = $this->property(
                'query',
                'string',
                'Free text to look for in: '.implode(', ', $resource->projection->searchable()).'.',
                true,
            );
        }

        if ($ability === 'list' && $resource->projection->filterable() !== []) {
            $lines[] = $this->property(
                'filters',
                'object',
                'Field to value pairs. Filterable fields: '.implode(', ', $resource->projection->filterable()).'.',
            );
        }

        if ($ability !== 'get') {
            $lines[] = $this->property(
                'limit',
                'integer',
                'Maximum rows to return. Capped at '.$resource->attribute->maxResults.' whatever is asked for.',
            );
        }

        if ($resource->relations() !== []) {
            $lines[] = $this->property(
                'include',
                'array',
                'Relations to expand, each returning only what that model itself exposes. '.
                'Available: '.implode(', ', $resource->relations()).'.',
            );
        }

        return implode("\n", $lines);
    }

    private function property(string $name, string $type, string $description, bool $required = false): string
    {
        $lines = [
            '            '.var_export($name, true).' => $schema->'.$type.'()',
            '                ->description('.var_export($description, true).')'.($required ? '' : ','),
        ];

        if ($required) {
            $lines[] = '                ->required(),';
        }

        return implode("\n", $lines);
    }
}
